INSERT INTO users (id, name, age) VALUES (1, "Erin", 20);
INSERT INTO users (id, name, age) VALUES (2, "Samantha", 22);
INSERT INTO users (id, name, age) VALUES (3, "Caleb", 24);
INSERT INTO users (id, name, age) VALUES (4, "Elry", 21);
INSERT INTO users (id, name, age) VALUES (5, "Phoebe", 20);
INSERT INTO users (id, name, age) VALUES (6, "Al", 33);
INSERT INTO users (id, name, age) VALUES (7, "Ryland", 27);
INSERT INTO users (id, name, age) VALUES (8, "Sarah", 28);
INSERT INTO users (id, name, age) VALUES (9, "Denise", 65);
INSERT INTO users (id, name, age) VALUES (10, "G-ma", 67);
INSERT INTO users (id, name, age) VALUES (11, "Tracy", 46);
INSERT INTO users (id, name, age) VALUES (12, "Jon Jon", 25);
INSERT INTO users (id, name, age) VALUES (13, "Mercy", 19);
INSERT INTO users (id, name, age) VALUES (14, "Keirah", 20);
INSERT INTO users (id, name, age) VALUES (15, "Reagan", 18);
INSERT INTO users (id, name, age) VALUES (16, "Mirna", 25);
INSERT INTO users (id, name, age) VALUES (17, "Omar", 25);
INSERT INTO users (id, name, age) VALUES (18, "BT", 23);
INSERT INTO users (id, name, age) VALUES (19, "Diego", 26);
INSERT INTO users (id, name, age) VALUES (20, "Latifah", 22);

INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "Science Project", "Science", 8000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Math Project", "Math", 6000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Art Project", "Art", 10000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "History Project", "History", 9000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "Music Project", "Music", 1000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Engineering Project", "Engineering", 3000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Marketing Project", "Marketing", 7000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "CS Project", "Computer Science", 4000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "English Project", "English", 5000, "2019-03-12", "2019-04-12" );
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Robotics Project", "Robotics", 2000, "2019-03-12", "2019-04-12" );

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 10.0, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 10.0, 1, 3);